### ISSUE TITLE
Fixing nerfed TNT velocity from slab mounting block

### ISSUE THREAD

**Issue by ryanwse** [OvercastNetwork/SportBukkit#206] opened 2016-07-12 00:29 UTC
Closing this since the network is shutting down in September.

**Comment by jedediah** [comment] 2016-07-12 03:27
The problem with slabs is not caused by that patch. Removing the patch happens to make TNT go farther, but it also completely breaks the occlusion mechanic that was working up until 1.8.

**Comment by kblanks** [comment] 2016-07-12 15:25
Even if his suggested fix wasn't the issue, surely the issue should still be open? It's clearly a problem that needs looking in to.

**Comment by kblanks** [comment] 2016-07-12 16:38
Thanks – didn't mean to seem hostile but thought it was silly to close it 👍

**Comment by pj1210** [comment] 2016-07-15 11:59
Please refer to this for more clarification: https://github.com/OvercastNetwork/Issues/issues/2504

**Comment by pj1210** [comment] 2016-07-15 12:02
@kblanks This problem is in no way related to OCN, Sportbukkit, or PGM as @jedediah said. It is more of a Minecraft bug that has been present since the 1.8.2 update. Reference: OvercastNetwork/Issues#2504

**Comment by pj1210** [comment] 2016-07-15 12:08
According to my research: When Mojang nerfed TNT in 1.8.0 and 1.8.1 compared to 1.7.10, Cubist made a bug report regarding this issue https://bugs.mojang.com/browse/MC-66089 (The provided cannons had a ladder, fence, and slabs for mounting blocks, yet only the cannons with slabs and fences were affected). When Mojang "resolved the bug" in 1.8.2, only cannons with the fence as a mounting block were fixed (reverted back to 1.7.10 range). Cannons with slabs on the other hand were "un-nerfed", but were still weaker (1.8.2) compared to 1.7.10. TNT on 1.8.2 was supposed to act like 1.7.10 as TNT on slabs were supposed to act similarly between 1.7.10 and 1.8.2, but sadly it did not. A possible reason is that TNT on slabs in 1.7.10 act differently from 1.8.2 when it was supposed to act the same.

I hope this clears things up. As for Sportbukkit 1.10, Cubist did the right thing to patch MC-100260 as it would ruin all of the cannons built on OCN.

**Closed** 2016-07-17 23:33 UTC

**Comment by pj1210** [comment] 2016-09-04 13:44
Could we reopen this since OCN is not shutting down anymore?

**Comment by itsmartin** [comment] 2016-10-01 09:45
@pj1210 we don't need to have this issue open on two separate trackers, we should keep this one closed in favour of https://github.com/OvercastNetwork/Issues/issues/2504.

**Comment by pj1210** [comment] 2016-10-03 11:39
@itsmartin sure! no problem
